---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - plugins/addPluginsMCSB.yaml
  - plugins/addPluginsPolicy.yaml
  - plugins/addPluginsPolicyNS.yaml
  - plugins/addPluginsPolicyPlacement.yaml
  - plugins/addPluginsPolicyPlacementBinding.yaml
  - operator/app-project.yaml
  - operator/argocd-application.yaml
  - operator/clusterrolebinding.yaml
  - operator/gitopsNS.yaml
  - operator/gitopsOperatorGroup.yaml
  - operator/gitopsSubscription.yaml
  #- operator/vss-git-creds.yaml
