---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mce-prereq
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
rules:
  - apiGroups:
      - ""
      - metal3.io
    resources:
      - namespace
      - configmaps
      - provisionings
      - secrets
    verbs:
      - get
      - list
      - patch
      - update
      - create
      - edit