---
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '100'
  name: ztp-gitops-link
spec:
  href: 'https://ztp-server-ztp.apps.hub1-jct.gmbros.local/'