---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: htpasswd-secret
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "30s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: htpasswd-secret
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    - extract:
        key: "gmbros/hub1/htpasswd"
