---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
  name: htpasswd-secret
  namespace: openshift-config
spec:
  type: kv-v2 
  mount: secret
  path: gmbros/hub1/htpasswd
  destination:
    name: htpasswd-secret
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-secrets-operator/vault-auth