---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../reference-crs/required/gitops/ztp-installation/

patches:
  - target:
      group: console.openshift.io
      version: v1
      kind: ConsoleLink
      name: ztp-gitops-link
    path: consolelink-patch.yaml
