---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    vault:
      server: "http://vault.vault-secrets-operator.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: kubernetes
          role: gmbros
          secretRef:
            name: default-sa-token
            namespace: vault-secrets-operator
            key: token
