---
apiVersion: operator.openshift.io/v1alpha1
kind: ExternalSecretsConfig
metadata:
  labels:
    app: external-secrets-operator
    app.kubernetes.io/name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: cluster
spec:
  controllerConfig:
    networkPolicies:
    - name: allow-external-secrets-egress
      componentName: ExternalSecretsCoreController
      egress: 
        # Allow egress to Kubernetes API server, AWS endpoints, and DNS
        - ports:
            # - port: 443   # HTTPS (AWS Secrets Manager)
            #   protocol: TCP
            - port: 8200   # Vault (HTTP)
              protocol: TCP
