---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vaultconnection.yaml
  - vaultauth.yaml
  - vaultNS.yaml
  - vaultOperatorGroup.yaml
  - vaultSubscription.yaml
  - route.yaml

helmCharts:
  - name: vault
    releaseName: vault
    namespace: vault-secrets-operator
    repo: https://helm.releases.hashicorp.com
    version: 0.28.0
    valuesInline:
      global:
        openshift: true
      server:
        dev:
          enabled: false
        ui:
          enabled: true
        dataStorage:
          enabled: true
          size: 10Gi
          storageClass: "lvms-data-lab-vg1" 
        auditStorage:
          enabled: true
        ha:
          enabled: true
          replicas: 1
          raft:
            enabled: true
            setNodeId: true

patches:
  - target:
      labelSelector: "app.kubernetes.io/instance=vault"
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "-35"