---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
  namespace: vault-secrets-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  allowedNamespaces:
    - "*"
  kubernetes:
    role: webapp
    serviceAccount: default
  method: kubernetes
  mount: kubernetes
  vaultConnectionRef: default
