---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - lvm-cluster.yaml
  - storage-cluster.yaml
  - storageNS.yaml
  - storageOperatorGroup.yaml
  - storageSubscription.yaml
