apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: my-lvm-cluster
  namespace: openshift-lvm-storage
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
spec:
  storage:
    deviceClasses:
      - default: true
        deviceSelector:
          forceWipeDevicesAndDestroyAllData: true
          paths:
            - /dev/sdb #TBC
        fstype: xfs
        name: data-lab-vg1
        thinPoolConfig:
          chunkSizeCalculationPolicy: Static
          metadataSizeCalculationPolicy: Host
          name: thin-pool-1
          overprovisionRatio: 10
          sizePercent: 90

