---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-45"
  name: openshift-storage
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-45"
  name: openshift-lvm-storage
  labels:
    openshift.io/cluster-monitoring: "true"