---
apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
  name: agent
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  databaseStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 15Gi
    storageClassName: "lvms-data-lab-vg1"
  filesystemStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
    storageClassName: "lvms-data-lab-vg1"
  # mirrorRegistryRef:
  #   name: mirror-registry-config
  # OSImageCACertRef:
  #   name: http-server-ca
  osImages:
    - openshiftVersion: "4.20"
      url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.20/latest/rhcos-4.20.11-x86_64-live-iso.x86_64.iso
      rootFSUrl: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.20/latest/rhcos-4.20.11-x86_64-live-rootfs.x86_64.img
      # pick version from https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/4.20.0/release.txt
      version: 9.6.20250925-0
      cpuArchitecture: "x86_64"
