apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: openshift-mirror
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  releaseImage: "quay.io/openshift-release-dev/ocp-release:4.20.0-x86_64"
