---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: multicluster-engine-pull-secret
  namespace: multicluster-engine
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "30s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: assisted-deployment-pull-secret
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    - extract:
        key: "gmbros/sno1/pull-secret"
