---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - acmNS.yaml
  - acmOperGroup.yaml
  - acmSubscription.yaml
  - acmMCH.yaml
  - acmMCE.yaml
  - acmAgentServiceConfig.yaml
  - acmPerfSearch.yaml
  - acmProvisioning.yaml
  - clusterimageset.yaml
  - job-ai-prereqs.yaml
  - rbac-job-ai/role.yaml
  - rbac-job-ai/rolebinding.yaml
  - rbac-job-ai/serviceAccount.yaml
 