---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: multicluster-engine-pull-secret
  namespace: multicluster-engine
spec:
  type: kv-v2 
  mount: secret
  path: gmbros/sno1/pull-secret
  destination:
    name: assisted-deployment-pull-secret
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-secrets-operator/vault-auth